[manager]
ratio = [1,3,3]
# show_hidden = true
sort_by = "size"
sort_sensitive = false
sort_reverse=true
linemode = "size"

[preview]
max_width = 1800
max_height = 1800

[open]
prepend_rules = [
{name = "*.html", use = ["open", "edit"]},
]
